# Configuration file for Codecov to manage coverage reporting and comments.
# - Defines coverage targets, thresholds, and exclusions.
# - Excludes certain directories from coverage calculations.
# - Configures comment layout and behavior for pull requests.
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 70%
        base: auto
ignore:
  - 'tests/*'
  - 'docs/*'
comment:
  layout: " diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false